import { describe, expect, it } from "vitest";
import { POSE_LANDMARK_NAMES, type PoseFrame, type PoseLandmark } from "../domain/models";
import { analyzeGait, calculateJointAngles, representativeWaveform } from "./gaitAnalysis";
import { processLandmarks } from "./landmarkProcessor";
import type { GaitCycle } from "./types";

function walkingFrames(seconds = 8, fps = 30): PoseFrame[] {
  return Array.from({ length: Math.round(seconds * fps) }, (_, frameIndex) => {
    const time = frameIndex / fps;
    const pelvisX = 0.25 + 0.05 * time;
    const landmarks = POSE_LANDMARK_NAMES.map<PoseLandmark>((name, index) => {
      const sidePhase = name.includes("left") ? 0 : Math.PI;
      const swing = 0.08 * Math.sin(2 * Math.PI * time + sidePhase);
      let x = pelvisX; let y = 0.25; let z = 0;
      if (name.includes("shoulder")) { x += 0.01 * Math.sin(2 * Math.PI * time + sidePhase); y = 0.30; z = name.includes("left") ? -0.35 : 0.35; }
      else if (name.includes("hip")) y = 0.50;
      else if (name.includes("knee")) { x += 0.45 * swing; y = 0.68; }
      else if (name.includes("ankle")) { x += 0.8 * swing; y = 0.86; }
      else if (name.includes("heel")) { x += swing; y = 0.91; }
      else if (name.includes("foot_index")) { x += swing + 0.03; y = 0.91; }
      return { index, name, x, y, z, visibility: 0.95, presence: null, worldX: null, worldY: null, worldZ: null };
    });
    return { frameIndex, timestampMs: Math.round(time * 1000), landmarks, frameWidth: 640, frameHeight: 640 };
  });
}

describe("Windows gait-analysis parity", () => {
  it("uses the same three joint definitions and same-side IC cycles", () => {
    const result = analyzeGait(walkingFrames());
    expect(result.viewpoint.analysisSupported).toBe(true);
    expect(result.direction).toBe("right");
    expect(result.events.some((event) => event.eventType === "IC")).toBe(true);
    expect(result.events.some((event) => event.eventType === "TO")).toBe(true);
    // The expected values below are generated by the current Windows Python
    // pipeline from this same synthetic timeline (SciPy/MediaPipe-independent).
    expect(result.events).toHaveLength(32);
    expect(result.cycles).toHaveLength(14);
    expect(new Set(result.angles.map((point) => point.joint))).toEqual(new Set([
      "hip_flexion", "knee_flexion", "ankle_dorsiflexion"
    ]));
    expect(new Set(result.angles.map((point) => point.side))).toEqual(new Set(["left", "right"]));
    expect(result.cycles.every((cycle) => Math.abs(cycle.endMs - cycle.startMs - 1000) <= 40)).toBe(true);
    expect(result.processing.presenceFallback).toBe(true);
    expect(result.acquisitionQuality.status).toBe("high");
    const windowsRanges = {
      hip_flexion: [-14.096, 14.096, 28.192],
      knee_flexion: [0, 2.455, 2.455],
      ankle_dorsiflexion: [-8.794, 8.794, 17.588]
    } as const;
    for (const [joint, expected] of Object.entries(windowsRanges)) {
      const values = result.angles.filter((point) => point.joint === joint).map((point) => point.angleDegrees);
      expect(values).toHaveLength(480);
      const minimum = Math.min(...values); const maximum = Math.max(...values);
      expect(minimum).toBeCloseTo(expected[0], 1);
      expect(maximum).toBeCloseTo(expected[1], 1);
      expect(maximum - minimum).toBeCloseTo(expected[2], 1);
      expect(result.jointQuality.find((quality) => quality.joint === joint)?.status).toBe("high");
    }
  });

  it("keeps a neutral heel-to-toe axis at zero ankle dorsiflexion", () => {
    const landmarks = POSE_LANDMARK_NAMES.map<PoseLandmark>((name, index) => ({
      index, name, x: 0, y: 0, z: 0, visibility: 0.95, presence: 0.95,
      worldX: null, worldY: null, worldZ: null
    }));
    for (const [index, coordinates] of new Map<number, [number, number]>([
      [11, [0, 0]], [23, [0, 1]], [25, [0, 2]], [27, [0, 3]], [29, [0, 3.1]], [31, [1, 3.1]]
    ])) {
      landmarks[index] = { ...landmarks[index]!, x: coordinates[0], y: coordinates[1] };
    }
    const cycles: GaitCycle[] = [{ side: "left", startMs: 0, endMs: 1000, toeOffMs: 600, confidence: 0.9 }];
    const ankle = calculateJointAngles([{ timestampMs: 500, landmarks, frameWidth: 640, frameHeight: 640 }], cycles, "right")
      .find((point) => point.side === "left" && point.joint === "ankle_dorsiflexion");
    expect(ankle?.angleDegrees).toBeCloseTo(0, 3);
  });

  it("uses rotation-corrected pixel geometry instead of distorted normalized coordinates", () => {
    const landmarks = POSE_LANDMARK_NAMES.map<PoseLandmark>((name, index) => ({
      index, name, x: 0.5, y: 0.2, z: 0, visibility: 0.95, presence: 0.95,
      worldX: null, worldY: null, worldZ: null
    }));
    const coordinates = new Map<number, [number, number]>([
      [11, [0.5, 0.2]], [23, [0.5, 0.4]], [25, [0.6125, 0.6]],
      [27, [0.65, 0.8]], [29, [0.65, 0.85]], [31, [0.75, 0.85]]
    ]);
    for (const [index, [x, y]] of coordinates) landmarks[index] = { ...landmarks[index]!, x, y };
    const cycles: GaitCycle[] = [{ side: "left", startMs: 0, endMs: 1000, toeOffMs: 600, confidence: 0.9 }];
    const hip = calculateJointAngles([
      { timestampMs: 500, landmarks, frameWidth: 640, frameHeight: 360 }
    ], cycles, "right").find((point) => point.side === "left" && point.joint === "hip_flexion");
    expect(hip?.angleDegrees).toBeCloseTo(45, 3);
  });

  it("keeps hip and knee available when only the foot landmarks are missing", () => {
    const frame = walkingFrames(1, 1)[0]!;
    const landmarks = frame.landmarks.filter((landmark) => ![29, 31].includes(landmark.index));
    const cycles: GaitCycle[] = [{ side: "left", startMs: 0, endMs: 1000, toeOffMs: 600, confidence: 0.9 }];
    const joints = calculateJointAngles([
      { ...frame, timestampMs: 500, landmarks }
    ], cycles, "right").filter((point) => point.side === "left").map((point) => point.joint);
    expect(joints).toContain("hip_flexion");
    expect(joints).toContain("knee_flexion");
    expect(joints).not.toContain("ankle_dorsiflexion");
  });

  it("provides hidden 4/6/8 Hz validation without changing the clinical result", () => {
    const result = analyzeGait(walkingFrames(5), { validationMode: true });
    expect(new Set(result.filterValidation.map((item) => item.cutoffHz))).toEqual(new Set([4, 6, 8]));
    expect(result.versions.angleDefinitionVersion).toBe("sagittal-pixel-v2");
    expect(result.versions.eventDetectorVersion).toBe("multisignal-v2");
    expect(representativeWaveform(result.angles, "knee_flexion", "left", "median").length).toBeGreaterThan(20);
    expect(representativeWaveform(result.angles, "knee_flexion", "left", "mean").length).toBeGreaterThan(20);
  });

  it("is deterministic and never overwrites raw Pose input", () => {
    const frames = walkingFrames(5);
    const before = structuredClone(frames);
    expect(analyzeGait(frames)).toEqual(analyzeGait(frames));
    expect(frames).toEqual(before);
  });

  it("withholds the clinical graph when foot tracking is not usable", () => {
    const frames = walkingFrames(5).map((frame) => ({
      ...frame,
      landmarks: frame.landmarks.map((landmark) => [27, 28, 29, 30, 31, 32].includes(landmark.index)
        ? { ...landmark, visibility: 0.1, presence: 0.1 } : landmark)
    }));
    const result = analyzeGait(frames, { cameraSide: "left" });
    expect(result.acquisitionQuality.status).toBe("retake");
    expect(result.acquisitionQuality.reasons.some((reason) => reason.includes("踵・足先"))).toBe(true);
  });

  it("recommends retaking a portrait video after automatic metadata review", () => {
    const result = analyzeGait(walkingFrames(5), { videoMetadata: {
      sourceWidth: 1080, sourceHeight: 1920, frameWidth: 640, frameHeight: 640,
      estimatedFps: 60, timestampSource: "presentation_timestamps", averageBrightness: 100,
      lowBrightnessRate: 0, analyzedFrameCount: 300
    } });
    expect(result.acquisitionQuality.status).toBe("retake");
    expect(result.acquisitionQuality.reasons.some((reason) => reason.includes("横向き"))).toBe(true);
  });

  it("removes a one-frame landmark excursion before zero-phase smoothing", () => {
    const frames = walkingFrames(4, 60);
    frames[90]!.landmarks[25] = { ...frames[90]!.landmarks[25]!, x: 2 };
    const processed = processLandmarks(frames);
    expect(processed.report.replacedOutliers).toBeGreaterThan(0);
    expect(processed.report.filterOrder).toBe(4);
    expect(processed.report.cutoffHz).toBe(6);
    expect(processed.report.zeroPhase).toBe(true);
  });
});
